apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-api
  namespace: security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: security-api
  template:
    metadata:
      labels:
        app: security-api
    spec:
      containers:
      - name: security-api
        image: jeffrygonzalez/security-demo:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
