apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: security-api-ingress
  labels:
    name: security-api-ingress
spec:
  rules:
  - host: security.company.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: security-api-service
            port: 
              number: 1339
