services:

  wiremock:
    image: "wiremock/wiremock:3.10.0"
    container_name: my_wiremock
    ports:
      - "8443:8443"
      - "8080:8080"
    volumes:
      - ./mocks/__files:/home/wiremock/__files
      - ./mocks/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh",  "--disable-gzip", "--https-port=8443", "http-port=8080", "--record-mappings", "--enable-stub-cors", "--verbose" ]
  db:
    image: postgres:16.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    environment:
      ADMINER_DESIGN: dracula
volumes:
  db_data: 